// <auto-generated />
using FinalFantasy.RepositoryEF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinalFantasy.RepositoryEF.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20210709072045_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinalFantasy.Core.Arma", b =>
                {
                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PuntiDanno")
                        .HasColumnType("int");

                    b.HasKey("Nome");

                    b.ToTable("Arma");

                    b.HasData(
                        new
                        {
                            Nome = "Ascia",
                            PuntiDanno = 8
                        },
                        new
                        {
                            Nome = "Mazza",
                            PuntiDanno = 5
                        },
                        new
                        {
                            Nome = "Spada",
                            PuntiDanno = 10
                        },
                        new
                        {
                            Nome = "Arco e frecce",
                            PuntiDanno = 8
                        },
                        new
                        {
                            Nome = "Bacchetta",
                            PuntiDanno = 5
                        },
                        new
                        {
                            Nome = "Bastone Magico",
                            PuntiDanno = 10
                        },
                        new
                        {
                            Nome = "Arco",
                            PuntiDanno = 7
                        },
                        new
                        {
                            Nome = "Clava",
                            PuntiDanno = 5
                        },
                        new
                        {
                            Nome = "Divinazione",
                            PuntiDanno = 15
                        },
                        new
                        {
                            Nome = "Fulmine",
                            PuntiDanno = 10
                        },
                        new
                        {
                            Nome = "Tempesta",
                            PuntiDanno = 8
                        });
                });

            modelBuilder.Entity("FinalFantasy.Core.Eroe", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<int>("Livello")
                        .HasColumnType("int");

                    b.Property<string>("NickNameGamer")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeArma")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PuntiLivello")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("NickNameGamer");

                    b.HasIndex("NomeArma");

                    b.ToTable("Eroe");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Categoria = 0,
                            Livello = 1,
                            NickNameGamer = "Laura_Pennetta",
                            Nome = "Furetto con il Fioretto",
                            NomeArma = "Spada",
                            PuntiLivello = 20
                        },
                        new
                        {
                            ID = 2,
                            Categoria = 1,
                            Livello = 2,
                            NickNameGamer = "Laura_Pennetta",
                            Nome = "Bisoretta",
                            NomeArma = "Bacchetta",
                            PuntiLivello = 33
                        },
                        new
                        {
                            ID = 3,
                            Categoria = 0,
                            Livello = 3,
                            NickNameGamer = "Laura_Pennetta",
                            Nome = "Uccellino Malandrino",
                            NomeArma = "Ascia",
                            PuntiLivello = 65
                        },
                        new
                        {
                            ID = 4,
                            Categoria = 0,
                            Livello = 4,
                            NickNameGamer = "Laura_Pennetta",
                            Nome = "Il gatto con gli stivali",
                            NomeArma = "Mazza",
                            PuntiLivello = 99
                        },
                        new
                        {
                            ID = 5,
                            Categoria = 1,
                            Livello = 5,
                            NickNameGamer = "Laura_Pennetta",
                            Nome = "Fiona",
                            NomeArma = "Arco e frecce",
                            PuntiLivello = 130
                        });
                });

            modelBuilder.Entity("FinalFantasy.Core.Gamer", b =>
                {
                    b.Property<string>("NickName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("NickName");

                    b.ToTable("Gamer");

                    b.HasData(
                        new
                        {
                            NickName = "Laura_Pennetta"
                        });
                });

            modelBuilder.Entity("FinalFantasy.Core.Mostro", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<int>("Livello")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeArma")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("NomeArma");

                    b.ToTable("Mostro");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Categoria = 1,
                            Livello = 1,
                            Nome = "Pollo Agguerrito",
                            NomeArma = "Clava"
                        },
                        new
                        {
                            ID = 2,
                            Categoria = 0,
                            Livello = 2,
                            Nome = "Gallinella Urlante",
                            NomeArma = "Tempesta"
                        },
                        new
                        {
                            ID = 3,
                            Categoria = 1,
                            Livello = 3,
                            Nome = "Fantasma Formaggino",
                            NomeArma = "Arco"
                        },
                        new
                        {
                            ID = 4,
                            Categoria = 0,
                            Livello = 4,
                            Nome = "Lupo MangiaFrutta",
                            NomeArma = "Fulmine"
                        },
                        new
                        {
                            ID = 5,
                            Categoria = 0,
                            Livello = 5,
                            Nome = "LucifeRutto",
                            NomeArma = "Divinazione"
                        });
                });

            modelBuilder.Entity("FinalFantasy.Core.Eroe", b =>
                {
                    b.HasOne("FinalFantasy.Core.Gamer", "Gamer")
                        .WithMany("Eroi")
                        .HasForeignKey("NickNameGamer");

                    b.HasOne("FinalFantasy.Core.Arma", "Arma")
                        .WithMany("Eroi")
                        .HasForeignKey("NomeArma");

                    b.Navigation("Arma");

                    b.Navigation("Gamer");
                });

            modelBuilder.Entity("FinalFantasy.Core.Mostro", b =>
                {
                    b.HasOne("FinalFantasy.Core.Arma", "Arma")
                        .WithMany("Mostri")
                        .HasForeignKey("NomeArma");

                    b.Navigation("Arma");
                });

            modelBuilder.Entity("FinalFantasy.Core.Arma", b =>
                {
                    b.Navigation("Eroi");

                    b.Navigation("Mostri");
                });

            modelBuilder.Entity("FinalFantasy.Core.Gamer", b =>
                {
                    b.Navigation("Eroi");
                });
#pragma warning restore 612, 618
        }
    }
}
